# Default configuration for blnk
default_api: openai
default_models:
  openai: gpt-4o
  anthropic: claude-3-5-sonnet-20241022
  gemini: gemini-2.0-flash-exp

max_tokens:
  openai: 2000
  anthropic: 1000
  gemini: 1000

# API keys will be stored here after setup
api_keys: {}